"""
Render a Markdown report + figures into a simple PDF.

- Input: report.md (generated by agent.py)
- Figures: folder with PNGs (generated by agent.py)
- Output: report.pdf

This is intentionally "no-magic": it doesn't try to fully parse Markdown.
It supports:
  - Title (# ...)
  - Section headings (## ...)
  - Bullets (- ...)
  - Plain paragraphs
  - Inline code (surrounded by backticks) rendered in monospace
And it embeds available figures at the end (or per marker).

Requires: reportlab
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Iterable

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfgen import canvas


def _register_fonts() -> None:
    # Use built-ins if Inter isn't available. Keep PDF generation dependency-light.
    # If you want Inter, drop Inter-Regular.ttf into ./fonts and register it here.
    try:
        fonts_dir = Path(__file__).resolve().parent / "fonts"
        inter = fonts_dir / "Inter-Regular.ttf"
        inter_bold = fonts_dir / "Inter-Bold.ttf"
        if inter.exists() and inter_bold.exists():
            pdfmetrics.registerFont(TTFont("Inter", str(inter)))
            pdfmetrics.registerFont(TTFont("Inter-Bold", str(inter_bold)))
    except Exception:
        pass


def _wrap_text(text: str, max_chars: int) -> list[str]:
    # Simple wrap by chars; good enough for clean reports.
    words = text.split()
    lines, cur = [], []
    cur_len = 0
    for w in words:
        add = len(w) + (1 if cur else 0)
        if cur_len + add > max_chars:
            lines.append(" ".join(cur))
            cur, cur_len = [w], len(w)
        else:
            cur.append(w)
            cur_len += add
    if cur:
        lines.append(" ".join(cur))
    return lines


def _draw_paragraph(c: canvas.Canvas, x: float, y: float, text: str, font: str, size: int, max_width_chars: int) -> float:
    c.setFont(font, size)
    for line in _wrap_text(text, max_width_chars):
        c.drawString(x, y, line)
        y -= size * 1.35
    return y


def render_pdf(report_md: Path, figures_dir: Path, out_pdf: Path) -> None:
    _register_fonts()

    page_w, page_h = A4
    left = 2.0 * cm
    right = 2.0 * cm
    top = 2.0 * cm
    bottom = 2.0 * cm

    c = canvas.Canvas(str(out_pdf), pagesize=A4)
    y = page_h - top

    title_font = "Inter-Bold" if "Inter-Bold" in pdfmetrics.getRegisteredFontNames() else "Helvetica-Bold"
    body_font = "Inter" if "Inter" in pdfmetrics.getRegisteredFontNames() else "Helvetica"
    mono_font = "Courier"

    # Header line
    c.setFont(body_font, 9)
    c.drawRightString(page_w - right, page_h - 1.2 * cm, "Demo 05 • Relatório gerado por agente • MentorDados")
    y -= 1.0 * cm

    md = report_md.read_text(encoding="utf-8").splitlines()
    for raw in md:
        line = raw.rstrip()
        if not line.strip():
            y -= 6
            continue

        # Page break
        if y < bottom + 4 * cm:
            c.showPage()
            y = page_h - top

        if line.startswith("# "):
            y -= 4
            c.setFont(title_font, 18)
            c.drawString(left, y, line[2:].strip())
            y -= 18 * 1.4
            continue

        if line.startswith("## "):
            y -= 2
            c.setFont(title_font, 13)
            c.drawString(left, y, line[3:].strip())
            y -= 13 * 1.6
            continue

        if line.startswith("- "):
            # Bullet
            text = line[2:].strip()
            # Handle inline code in a minimal way: split by backticks.
            parts = re.split(r"(`[^`]+`)", text)
            x = left
            c.setFont(body_font, 10)
            c.drawString(x, y, "• ")
            x += 12
            for p in parts:
                if not p:
                    continue
                if p.startswith("`") and p.endswith("`"):
                    c.setFont(mono_font, 9)
                    c.drawString(x, y, p[1:-1])
                    x += c.stringWidth(p[1:-1], mono_font, 9) + 4
                    c.setFont(body_font, 10)
                else:
                    c.setFont(body_font, 10)
                    c.drawString(x, y, p)
                    x += c.stringWidth(p, body_font, 10)
            y -= 10 * 1.6
            continue

        # Paragraph
        y = _draw_paragraph(c, left, y, line, body_font, 10, max_width_chars=105)

    # Figures
    figs = sorted([p for p in figures_dir.glob("*.png")]) if figures_dir.exists() else []
    if figs:
        if y < bottom + 6 * cm:
            c.showPage()
            y = page_h - top
        c.setFont(title_font, 13)
        c.drawString(left, y, "Figuras")
        y -= 13 * 1.6

        for fig in figs:
            # Keep aspect ratio, max width ~ (page_w - margins)
            max_w = page_w - left - right
            max_h = 8.5 * cm
            # reportlab needs PIL for image size reading sometimes; keep it simple:
            # We'll try embedding with a safe box, letting reportlab scale.
            if y < bottom + max_h:
                c.showPage()
                y = page_h - top
            c.setFont(body_font, 9)
            c.drawString(left, y, fig.name)
            y -= 10
            c.drawImage(str(fig), left, y - max_h, width=max_w, height=max_h, preserveAspectRatio=True, anchor="n")
            y -= max_h + 16

    c.save()


if __name__ == "__main__":
    import argparse

    ap = argparse.ArgumentParser()
    ap.add_argument("--report", required=True, help="Path to report.md")
    ap.add_argument("--figures", required=True, help="Path to figures folder")
    ap.add_argument("--out", required=True, help="Path to output PDF")
    args = ap.parse_args()

    render_pdf(Path(args.report), Path(args.figures), Path(args.out))
